### ISSUE TITLE
Scale prop not working

### ISSUE THREAD

**Issue by hammermaxmann** [hrynko/vue-pdf-embed#239]
**Steps to reproduce:**

See https://jsfiddle.net/3k60c5o4/2/
Add a scale prop;
```html
  <vue-pdf-embed source="https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf" :scale="2" />
```

Text will only get really unsharp without dimension changing. See canvas element - specific css width/height (which stays the same) is overwriting the canvas "width" and "height" attributes.

**Working fix:**

Remove setting css attributes to the canvas, then it will scale correctly.

For an example add following CSS somewhere:

```css
canvas {
  width: unset !important;
  height: unset !important;
 }
 ```
